.TH "config" 3 "Version 2.0.1" "wordlistctl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBuseragent\fP [256]"
.br
.ti -1c
.RI "char \fBdownload_path\fP [512]"
.br
.ti -1c
.RI "int \fBworkers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configuration structure for wordlistctl

.PP
This structure holds the user agent string, the default download path and the number of workers used to download the files\&. 
.SH "Field Documentation"
.PP 
.SS "char config::download_path[512]"
Default download path 
.SS "char config::useragent[256]"
User agent string 
.SS "int config::workers"
Number of workers used to download the files 

.SH "Author"
.PP 
Generated automatically by Doxygen for wordlistctl from the source code\&.
